const VALID_NEWS_DOMAINS = new Set([
  'bbc.com',
  'nytimes.com',
  'theguardian.com',
  'cnn.com',
  'reuters.com',
  'washingtonpost.com',
  'ap.org',
  'npr.org',
  'aljazeera.com',
  'usatoday.com',
  'wsj.com',
  'theindependent.co.uk',
  'bloomberg.com',
  'latimes.com',
  'thetimes.co.uk',
  'telegraph.co.uk',
  'huffpost.com',
  'economist.com',
  'newyorker.com',
  'time.com',
  'factcheck.org',
  'politifact.com',
  'snopes.com',
  'poynter.org',
  'fullfact.org',
  'leadstories.com',
  'sciencefeedback.co',
  'checkyourfact.com',
  'mediabiasfactcheck.com',
  'cbc.ca',
  'sky.com',
  'theaustralian.com.au',
  'dw.com',
  'france24.com',
  'japantimes.co.jp',
  'smh.com.au',
  'thehindu.com',
  'economictimes.indiatimes.com',
  'foxnews.com',
  'abcnews.go.com',
  'theverge.com',
  'buzzfeed.com',
  'washingtonexaminer.com',
  'thehill.com',
  'msnbc.com',
  'forbes.com',
  'newsweek.com',
  'huffpost.co.uk',
  'worldometers.info',
  'thedailybeast.com',
  'vox.com',
  'theweek.com',
  'businessinsider.com',
  'breaking911.com',
  'today.com',
  'techcrunch.com',
  'thewrap.com',
  'tmz.com',
  'thr.com',
  'variety.com',
  'nydailynews.com',
  'thediplomat.com',
  'cnbc.com',
  'bbc.co.uk',
  'reuters.co.uk',
  'rfi.fr',
  'republicworld.com',
  'independent.co.uk',
  'boston.com',
  'seattletimes.com',
  'chronicle.com',
  'startribune.com',
  'dallasnews.com',
  'detroitnews.com',
  'sfchronicle.com',
  'news.com.au',
  'heraldsun.com.au',
  'theage.com.au',
  'brisbanetimes.com.au',
  'newsday.com',
  'wapo.st',
  'people.com',
  'cbsnews.com',
  'businessweek.com',
  'marketwatch.com',
  'newstatesman.com',
  'globeeconomics.com',
  'politico.com',
  'scmp.com',
  'businessinsider.in',
  'screenrant.com',
  'cleveland.com',
  'denverpost.com',
  'hawaiinewsnow.com',
  'baltimoresun.com',
  'sun-sentinel.com',
  'orlandosentinel.com',
  'beaconjournal.com',
  'stltoday.com',
  'mailonline.com',
  'breakingnews.com',
  'texastribune.org',
  'financialexpress.com',
  'thenewslens.com',
  'thefinancialexpress.com',
  'gulfnews.com',
  'al.com',
  'theconversation.com',
  'newscorp.com',
  'foxbusiness.com',
  'foxsports.com',
  'radionz.co.nz',
  'freep.com',
  'abc.net.au',
  'thedrum.com',
  'techradar.com',
  'guardian.co.uk',
  'ft.com',
  'thestar.com',
  'sports.yahoo.com',
  'livescience.com',
  'sciencedaily.com',
  'scientificamerican.com',
  'newser.com',
  'themanitobapost.com',
  'truthout.org',
  'buzzfeednews.com',
  'themercurynews.com',
  'wbur.org',
  'wxyz.com',
  'nbcnews.com',
  'abcnews.com',
  'usnews.com',
  'sfgate.com',
  'chicagotribune.com',
  'news.sky.com',
  'ourquadcities.com',
  'news4jax.com',
  'azcentral.com',
  'theathletic.com',
  'dailycaller.com',
  'breitbart.com',
  'thedailycaller.com',
  'infowars.com',
  'washingtontimes.com',
  'theblaze.com',
  'libertyunyielding.com',
  'heraldtribune.com',
  'europarl.europa.eu',
  'thelocal.it',
  'military.com',
  'townhall.com',
  'nationalreview.com',
  'theintercept.com',
  'morningconsult.com',
  'natlawreview.com',
  'fortune.com',
  'zocalopublicsquare.org',
  'stlouisfed.org',
  'electronicintifada.net',
  'telesurenglish.net',
  'euvsdisinfo.eu',
  'rttnews.com',
  'ppv.com',
  'republicanpost.net',
  'pressherald.com',
  'straitstimes.com',
  'dailywire.com'
]);

export const isValidNewsUrl = (url: string): { isValid: boolean; message?: string } => {
  try {
    // Add https:// if no protocol is specified
    const urlToCheck = url.startsWith('http://') || url.startsWith('https://')
      ? url
      : `https://${url}`;

    const urlObj = new URL(urlToCheck);
    const domain = urlObj.hostname.toLowerCase().replace(/^www\./, '');
    
    if (VALID_NEWS_DOMAINS.has(domain)) {
      return { isValid: true };
    }
    
    return { 
      isValid: false, 
      message: "Please enter a URL from a recognized news source. We currently support major news outlets like BBC, NYTimes, Reuters, etc."
    };
  } catch (err) {
    return { 
      isValid: false, 
      message: "Please enter a valid URL"
    };
  }
}; 